### ISSUE TITLE
Upon changing name, sensors duplications

### ISSUE THREAD

**Issue by stefanolarentis** [asednev/homebridge-plugin-govee#17]
Hi,

I love this plugin. I have been using Govee H5102 and it works perfectly. However once I decided to change the name of the humidity and temperature widgets on Homekit, a bug developed. After I changed the names two new widgets created with the old name, and they are stuck with the last temperature measurement before I changed the names.  I was unable to find a way to get rid of the duplicate/stuck sensors.

This also is replicated in the accessories window. See below.
![image](https://user-images.githubusercontent.com/35013107/105609217-614a2680-5d6d-11eb-8bb2-62dc81548298.png)

Thanks a lot!

**Comment by asednev** [comment]
Thank you for reporting this issue. I suspect the reason for this bug is a non-ASCII character used in the device name (rendered as a rectangle). I will look into filtering non-ASCII characters.

In the meantime, you should be able to delete the stuck accessory via settings for Homebridge. There's an option to delete a single cached accessory.

**Comment by stefanolarentis** [comment]
Thanks! Got rid of the cashed accessory in the UI. Thanks a lot!
